version: '3.8'

services:
  waiterapi:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - sqlite_data:/app/db.sqlite3
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=waiterapi.settings
    restart: unless-stopped
    stdin_open: true
    tty: true

volumes:
  sqlite_data: 