# Generated by Django 5.2.4 on 2025-07-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='table_number',
            field=models.CharField(blank=True, help_text='Table number for the order', max_length=10, null=True),
        ),
    ]
